name = ""
type = "javascript"
route = ""
# routes = [""]
zone_id = ""
usage_model = ""
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-28"

[build]
command = "npm install && npm run build"

[build.upload]
# Upload the code directly from the dist directory.
dir = "dist"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./worker.mjs"

#[durable_objects]
#bindings = [
#  {name = "DURABLE_OBJECTS_ENV_NAME", class_name = "DurableObjectsClassName"}
#]
